### ISSUE TITLE
initialize the package with an empty table state

### ISSUE THREAD

**Issue by AucaCoyan** [RobMayer/create-ttpg-package#1]
Hi!
I love the project, I am already using it! I'm on my way to develop a game in TTPG 🌱 

With the use, I realized that the startup doesnt give you a initial `assets/States/start.vts` or something.

So when you create a new mod, and start the editor, a warning is shown saying

```
Could not load saved state
invalid save file
```

What do you think? Is it reasonable?
Thanks!

**Comment by AucaCoyan** [comment]
This is a sample `.vts` file
<details>

```
{
	"saveStateVersion": "1.1",
	"gameState":
	{
		"measureUnit": 2.5399999618530273,
		"rotationStep": 45,
		"notes": "You can enter notes for the game here. They will be visible to all players and are stored when the game is saved.\n\nYou can use [color=#ff0000]colors[/color], [b]bold[/b] or [i]italic[/i] text, [size=9]different[/size] [size=16]sizes[/size], and [color=#00ff00][size=8][b][i]combine text styles.[/color][/size][/b][/i]",
		"turnInfo":
		{
		},
		"slotTeams": [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
		"globalScriptPackage": "00000000000000000000000000000000",
		"globalScriptName": "hello_world.js",
		"backgroundTexture":
		{
			"resourceName": "",
			"packageGuid": "00000000000000000000000000000000"
		},
		"phases": [],
		"spectatorsSeeEverything": false,
		"persistentData": "",
		"persistentKeyData":
		{
		},
		"permissions":
		{
			"delete": -1,
			"objectLibrary": -1,
			"copyPaste": -1,
			"cardPeek": -1,
			"cardExplorer": -1,
			"containerExplorer": -1,
			"changeOwner": -1,
			"changeTeam": -1,
			"editZones": -1,
			"draw": -1,
			"ground": -1,
			"throw": -1,
			"editLabels": -1,
			"saveGame": -1,
			"spectators": -1
		},
		"physicsLocked": false,
		"measureAngles": "None",
		"alwaysSnap": false,
		"liftOverRegular": true,
		"gravityMultiplier": 1,
		"slotIds": [
			"00028a7986104715ad744734c892c2b1",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		],
		"mapName": "HDRI_Field",
		"currentTurn": 0,
		"bCanBeDamaged": false
	},
	"requiredPackages": [
		{
			"name": "General",
			"guid": "D74C7D5D6745CD565913DAA5FB3E9C93"
		}
	],
	"storedCameraSetups": [ false, false, false, false, false, false, false, false, false, false ],
	"playerCameraSetups": [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ],
	"playerSlotNames": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13",
		"14",
		"15",
		"16",
		"17",
		"18",
		"19",
		"20"
	],
	"customPlayerColors": [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ],
	"lighting":
	{
		"intensity": 1,
		"specular": 1,
		"altitude": 90,
		"azimuth": 0,
		"color":
		{
			"r": 255,
			"g": 255,
			"b": 255
		}
	},
	"grid":
	{
		"type": 0,
		"snapType": 0,
		"visibility": 0,
		"size":
		{
			"x": 5.0799999237060547,
			"y": 5.0799999237060547
		},
		"offset":
		{
			"x": 0,
			"y": 0
		},
		"rotation": 0,
		"color":
		{
			"r": 0,
			"g": 0,
			"b": 0,
			"a": 179
		},
		"thickLines": false
	},
	"objects": [
		{
			"objectType": "Table",
			"transform":
			{
				"rotation":
				{
					"x": 0,
					"y": 0,
					"z": 0,
					"w": 1
				},
				"translation":
				{
					"x": 0,
					"y": 0,
					"z": 0
				},
				"scale3D":
				{
					"x": 1,
					"y": 1,
					"z": 1
				}
			},
			"simulatingPhysics": true,
			"primaryColor":
			{
				"b": 255,
				"g": 255,
				"r": 255,
				"a": 255
			},
			"secondaryColor":
			{
				"b": 0,
				"g": 0,
				"r": 0,
				"a": 255
			},
			"metallic": 0,
			"roughness": 1,
			"friction": 0.69999998807907104,
			"restitution": 0.30000001192092896,
			"density": 1,
			"surfaceType": "SurfaceType1",
			"objectName": "",
			"objectDescription": "",
			"collisionType": "CB_Static",
			"templateId": "F27689B0431FFA778EC9D6835FA2B8FC",
			"shouldSnap": true,
			"previousPosition":
			{
				"x": 0,
				"y": 0,
				"z": 0
			},
			"objectScriptPackage": "00000000000000000000000000000000",
			"objectScriptName": "",
			"persistentData": "",
			"persistentKeyData":
			{
			},
			"uniqueId": "nu2",
			"drawingLines": [],
			"objectTags": [],
			"objectGroupId": -1,
			"ownerIndex": -1,
			"lightsOn": true,
			"bCanBeDamaged": false
		}
	],
	"zones": [],
	"labels": []
}
```

</details>


_edit_: added the lines

```
		"globalScriptName": "hello_world.js",
```

to reference the main entrypoint

**Comment by RobMayer** [comment]
Sorry, I didn't notice this issue until now >.<

from a design standpoint: I'm a little hesitant to have the template create an initial Save State automatically. I see the logic, but consider the scenarios:

1) You need a save state for your mod, and the script provides a starter one: One would need to edit that initial state, or will end up deleting the initial state in favor of creating one themselves. It'd save you a mouse-click, maybe.
Also suppose one forgot about needing to create a save state (which I know I've done a few times) and go to publish. TTPG sees the default state and doesn't throw a warning because it sees the initial blank state. and so you've published your mod with a blank start state.

2) You need a save state for your mod, and the script *doesn't* provide one: you're not really that worse off: you'd just need to create one, which is arguably the same as having to edit an initial one. 
On the off chance that one forgets this step and you go to upload, TTPG will catch it and say "there is no save state, are you sure?" - saving you from uploading a mod without a save state. Otherwise, if you forget, and go to upload: you've got an empty save state because the template created the blank one, so TTPG never warns you.

3) You don't need a save state (which happens a lot for utility object-type mods; in fact 90% of mine don't have a save state at all, they're just meant to be imported individually) and the script provides one. At that point you have to remember to remove the initial state the script provides, otherwise TTPG will upload your mod without question and you've got a blank/empty state that serves no purpose and is, again, confusing for consumers.

4) You don't need a save state and the script *doesn't* provide one. When you go to upload, TTPG will ask "there is no start state: are you sure?" at which point you go "yup!" 

Having the template not provide an initial state seems the least "dangerous" (for a given measure of dangerous) and has the most safety in terms of double-checks. Providing one by default seems fraught with potential accidents and false positives.




As far as the error you're getting? I haven't seen that, but I've never really gone looking since it doesn't seem to interfere with my ability to edit a package. Can you share a bit of your process and share where you see that warning?

**Comment by AucaCoyan** [comment]
Hello again! First, thank you for being very thorough!
I see that it is more reasonable _not_ to create a save state than to create the package with an empty one.

As for the error I was getting, I tried with a new package and I couldn't reproduce it, so it was just some random error that sometime occurs. Don't worry!

Is it alright if we take a section on the `README.md` explaning this thing of the Save State?
I believe more than one dev will be confused if they also expect a Save State to be created with the package setup. What do you think?

**Comment by RobMayer** [comment]
Makes sense - I'll write something up in the coming days and add it to the readme :)
